# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class MonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_metric = channel.unary_unary(
                '/Monitor/get_metric',
                request_serializer=service__pb2.Nulo.SerializeToString,
                response_deserializer=service__pb2.Metric.FromString,
                )
        self.is_alive = channel.unary_unary(
                '/Monitor/is_alive',
                request_serializer=service__pb2.Nulo.SerializeToString,
                response_deserializer=service__pb2.Alive.FromString,
                )


class MonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_metric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_alive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_metric': grpc.unary_unary_rpc_method_handler(
                    servicer.get_metric,
                    request_deserializer=service__pb2.Nulo.FromString,
                    response_serializer=service__pb2.Metric.SerializeToString,
            ),
            'is_alive': grpc.unary_unary_rpc_method_handler(
                    servicer.is_alive,
                    request_deserializer=service__pb2.Nulo.FromString,
                    response_serializer=service__pb2.Alive.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Monitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Monitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_metric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Monitor/get_metric',
            service__pb2.Nulo.SerializeToString,
            service__pb2.Metric.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_alive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Monitor/is_alive',
            service__pb2.Nulo.SerializeToString,
            service__pb2.Alive.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
